-- MEX Poshta delivery zones — the mirror of get_cities.php.
--
-- MEX is the Macedonian courier replacing the inherited Bulgarian Speedy/Econt
-- stack. Their API exposes exactly five endpoints and NONE of them serve
-- streets, offices, tariffs or cancellation. get_cities.php is the only
-- reference data they publish: 149 rows for country_id=157 (Macedonia).
--
-- These are ROUTING ZONES, not a settlement register, and the distinction
-- matters for everything downstream:
--   * Skopje is exploded into ~60 neighbourhoods ("Skopje - Aerodrom"),
--     Tetovo into ~30 villages, but Kumanovo and Veles have ONE row each.
--   * Names are Latin-only and inconsistently transliterated — "Kicevo" sits
--     next to "Kočani", "Zhelino" next to "Vrapčište".
--   * The list contains genuine duplicates: city_id 117 "Stip" AND 143 "Štip";
--     261 "Skopje - Keramidnica" AND 289 "SKOPJE-KERAMIDNICA".
--
-- Macedonia has ~1.725 settlements. Mapping those onto these 149 zones is the
-- job of mk_settlements.mex_city_id (see 20260915000100) and
-- scripts/map-settlements-to-mex.mjs. This table is only the raw mirror.

CREATE TABLE IF NOT EXISTS public.mex_cities (
  -- MEX's own identifier. Never generated by us: add_shipment.php takes it
  -- verbatim as receiver_city_id, so it must survive refreshes untouched.
  city_id          integer PRIMARY KEY,
  city_name        text NOT NULL,
  -- normalizeMkGeo(city_name) — see scripts/lib/mk-translit.mjs. The join key
  -- that lets Cyrillic input, MEX's Latin and OSM's name:en all meet.
  city_name_norm   text NOT NULL,
  country_id       integer NOT NULL DEFAULT 157,
  country_code     text,
  -- Set false to retire a zone MEX has dropped. We never DELETE: a shipped
  -- order may still reference the id, and its history must stay readable.
  is_active        boolean NOT NULL DEFAULT true,
  -- Points at the surviving row when MEX ships the same town twice. The mapper
  -- only ever targets rows where this IS NULL, so the defect is neutralised
  -- once, here, instead of at every lookup.
  is_duplicate_of  integer REFERENCES public.mex_cities(city_id),
  -- An admin has adjudicated this row; the refresh script must not re-decide
  -- which member of a duplicate group is canonical.
  canonical_locked boolean NOT NULL DEFAULT false,
  refreshed_at     timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_mex_cities_norm
  ON public.mex_cities (city_name_norm text_pattern_ops);
CREATE INDEX IF NOT EXISTS idx_mex_cities_active
  ON public.mex_cities (is_active) WHERE is_duplicate_of IS NULL;

-- Hand-curated spellings the normaliser cannot and MUST NOT guess.
--
-- normalizeMkGeo deliberately refuses to collapse names that merely look
-- related: "Skopje - Aracinovo Haraçine" and "Skopje - Haracine" are the same
-- place under Macedonian and Albanian names, but "Kërçovë" and "Кичево" are too
-- far apart for any algorithm to equate safely. Guessing routes a parcel to the
-- wrong town, and MEX has no cancellation endpoint — so a human decides here.
--
-- This table survives every re-run of fetch-mex-cities.mjs.
CREATE TABLE IF NOT EXISTS public.mex_city_aliases (
  alias_norm  text PRIMARY KEY,               -- normalizeMkGeo of the alternate spelling
  mex_city_id integer NOT NULL REFERENCES public.mex_cities(city_id) ON DELETE CASCADE,
  note        text,                           -- why: "Albanian name", "MEX typo", …
  created_at  timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_mex_city_aliases_city
  ON public.mex_city_aliases (mex_city_id);

-- ── RLS ──────────────────────────────────────────────────────────────────────
-- Affiliates hold a REAL Supabase login and can query PostgREST directly with
-- their own JWT, so `authenticated USING (true)` is a hard wall bypass. Reuse
-- the same predicate as 20260802000200 / 20260904000010 — do not invent a
-- second one. Every server path uses the service-role client and bypasses RLS.
ALTER TABLE public.mex_cities       ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.mex_city_aliases ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Internal staff can read mex cities" ON public.mex_cities;
CREATE POLICY "Internal staff can read mex cities" ON public.mex_cities
  FOR SELECT TO authenticated USING (public.is_internal_staff(auth.uid()));

DROP POLICY IF EXISTS "Internal staff can read mex city aliases" ON public.mex_city_aliases;
CREATE POLICY "Internal staff can read mex city aliases" ON public.mex_city_aliases
  FOR SELECT TO authenticated USING (public.is_internal_staff(auth.uid()));
